# Comment to a new issue.
issuesOpened: > 
  issues 作成ありがとうございます。以下確認お願いいたします。
  ・やること は記入してありますか。
  ・完了の定義 は記入してありますか。
  ・Assignees は選択してありますか。
  ・Labels は選択してありますか。
  ・Projects は選択してありますか。
  ・上記問題なければ、Active branches に、「feature/issue-{issue.number}-potfy」という branch が生成されるので、そちらで作業をお願い致します。

pullRequestsOpened: >
  pull requests 作成ありがとうございます。以下確認お願いいたします。
  ・やったこと は記入してありますか。
  ・issue番号 は記入してありますか。
  ・Reviewers は選択してありますか。
  ・Assignees は選択してありますか。
