files:
  include: "**/*.s+(a|c)ss"
  ignore:
    - node_modules/**
syntax:
    include:
      - scss
      - sass

resolvers:
  bem-depth:
    - 0
    - max-depth: 1
  border-zero: 0
  class-name-format: 0
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: true
  final-newline:
    - 1
    - include: true
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  indentation:
    - 1
    - size: 1
  no-color-keywords: 1
  no-color-literals: 0
  no-css-comments: 1
  no-extends: 0
  no-important: 1
  no-trailing-zero: 1
  no-transition-all: 0
  no-url-domains: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  property-sort-order: 0
  space-after-bang:
    - 1
    - include: false
  space-after-colon:
    - 1
    - include: true
  space-before-bang:
    - 1
    - include: true
  space-before-colon: 1
  url-quotes: 1
  variable-for-property:
    - 0
    - properties: []
  zero-unit: 1
