name: Move new pull requests into WIP

on:
  pull_request:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Project Automation+
        uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: FirstReleaseProject
          column: WIP
          repo-token: ${{ secrets.GITHUB_TOKEN }}